[package]
name = 'userinfo'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
sender = "67FEEC357CF9B7FD46357F81923CFD087FF1CF1393E28C8886DF261781D6BEB7"
